EssentialCSharp10/Models/ErrorViewModel.cs
namespace EssentialCSharp10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EssentialCSharp10/Controllers/HomeController.cs
using EssentialCSharp10.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
//using EssentialCSharp10.Helpers;

namespace EssentialCSharp10.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

            var strValue = "This is a string";
            var sanitizedString = CommonHelperMethods.SanitizeString(strValue);
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EssentialCSharp10/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
//using EssentialCSharp10.Helpers;

namespace EssentialCSharp10.Controllers
{
    public class InfoController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public InfoController(ILogger<HomeController> logger)
        {
            _logger = logger;

            var strValue = "This is a string";
            var sanitizedString = CommonHelperMethods.SanitizeString(strValue);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

EssentialCSharp10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2 class="display-5">to ASP.NET Core 6.0 Succinctly</h2>
    <p>For the source code from this book, <a href="https://github.com/SyncfusionSuccinctlyE-Books/ASP.NET-Core-6-Succinctly">get it on GitHub</a>.</p>
</div>

EssentialCSharp10/Views/Info/Index.cshtml
@{
    ViewData["Title"] = "Information Page";
}

<div class="text-center">
    <h1 class="display-4">Information</h1>
    <p>For the source code from this book, <a href="https://github.com/SyncfusionSuccinctlyE-Books/ASP.NET-Core-6-Succinctly">get it on GitHub</a>.</p>
</div>

EssentialCSharp10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EssentialCSharp10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EssentialCSharp10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EssentialCSharp10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Index">Information</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EssentialCSharp10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>